[build]
  # We commit Flutter's web build output to git, so Netlify should just serve it.
  publish = "build/web"
  command = ""

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = true

[[headers]]
for = "/flutter_service_worker.js"
  [headers.values]
  Cache-Control = "no-cache, max-age=0, must-revalidate"

[[headers]]
for = "/main.dart.js"
  [headers.values]
  Cache-Control = "no-cache, max-age=0, must-revalidate"

